/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
 * Generated on: 13-Apr-2023 16:35:32
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 18
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,16 -> [-5.000000e-01 5.000000e-01)
 * Input             : s12,12 -> [-5.000000e-01 5.000000e-01)
 * Filter Internals  : Full Precision
 *   Output          : s29,28 -> [-1 1)  (auto determined)
 *   Product         : s27,28 -> [-2.500000e-01 2.500000e-01)  (auto determined)
 *   Accumulator     : s29,28 -> [-1 1)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
#include <stdint.h>

/*
 * Expected path to tmwtypes.h
 * D:\Program Files\extern\include\tmwtypes.h
 */

 //FILTRO PASABAJOS 20Hz 17 ORDEN 
#define BL = 18;
const int32_t B[18] = {
         2371,   1196,  -1380,  -3664,  -3591,      0,   6464,  13435,  17937,
    17937,  13435,   6464,      0,  -3591,  -3664,  -1380,   1196,   2371
};