/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
 * Generated on: 13-Apr-2023 15:45:04
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 12
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s16,17 -> [-2.500000e-01 2.500000e-01)
 * Input             : s12,12 -> [-5.000000e-01 5.000000e-01)
 * Filter Internals  : Full Precision
 *   Output          : s30,29 -> [-1 1)  (auto determined)
 *   Product         : s27,29 -> [-1.250000e-01 1.250000e-01)  (auto determined)
 *   Accumulator     : s30,29 -> [-1 1)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/*
 * Expected path to tmwtypes.h
 * D:\Program Files\extern\include\tmwtypes.h
 */
#include <stdint.h>

/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int16 filter coefficients.
 */

 //FILTRO PASABAJOS 15Hz 11 ORDEN 
#define BL = 12;
const int32_t B[12] = {
        -1809,    465,   3777,   7432,  10554,  12350,  12350,  10554,   7432,
     3777,    465,  -1809
};